# Generated by Django 3.2.7 on 2021-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Training Date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1, verbose_name='Meal Period'),
        ),
    ]
