# Generated by Django 3.2.7 on 2021-11-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211104_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercise',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1, verbose_name='Exercise Time:'),
        ),
    ]
